image: node:lts-bullseye
stages:
  - build
  - deploy

build:
  stage: build
  only:
    - main
  variables:
    BASE_URL: ''
  script:
    - npm install
    - CI=false npm run build
  artifacts:
    paths:
      - build
  tags:
    - spherity-app


deploy_netlify:
  image: node
  stage: deploy
  dependencies:
    - build
  only:
    - main
  script:
    - npm install netlify-cli -g
    - netlify deploy --prod --dir=build --site=b4dce4ca-fc03-445d-a91f-3dec7d92caa3
  tags:
    - spherity-app
